# Generated by Django 4.2.23 on 2025-07-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
