# Generated by Django 4.2.23 on 2025-07-01 06:27

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_otp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=patients.models.default_expiry),
        ),
    ]
