# Generated by Django 4.2.23 on 2025-07-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
    ]
